FROM rust:1.92.0
RUN rustup component add rustfmt
RUN apt-get update && apt-get install -y dumb-init

# Create safeuser with UID 1000
RUN useradd -m -u 1000 safeuser

# Switch to safeuser
USER safeuser

ENTRYPOINT ["dumb-init", "--"]